---
- hosts: all
  become: True
  gather_facts: False
  tasks:
          - name: Creating file,setting permissions and git bit
            file:
                    path: /root/mark_file
                    owner: mark
                    group: mark
                    mode: '2760'
                    state: touch
...                      

